# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount', models.IntegerField()),
                ('tags', models.CharField(max_length=125)),
                ('deadline', models.IntegerField()),
                ('project_image', models.ImageField(upload_to='uploads/project/%Y/%m/%d')),
                ('project_description', models.TextField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Categories')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
