# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('contrib_amount', models.IntegerField()),
                ('available', models.IntegerField()),
                ('delivery_date', models.DateTimeField(default=None)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'perk',
                'verbose_name_plural': 'perks',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount', models.IntegerField()),
                ('tags', models.CharField(max_length=125)),
                ('deadline', models.IntegerField()),
                ('project_image', models.ImageField(upload_to='project//%Y/%m/%d')),
                ('project_description', models.TextField(max_length=10000)),
                ('facebook_url', models.CharField(max_length=125)),
                ('twitter_url', models.CharField(max_length=125)),
                ('youtube_url', models.CharField(max_length=125)),
                ('site_url', models.CharField(max_length=125)),
                ('is_active', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Categories')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
