# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0002_auto_20170223_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount', models.IntegerField(max_length=15)),
                ('tags', models.CharField(max_length=125)),
                ('deadline', models.IntegerField(max_length=3)),
                ('project_image', models.ImageField(upload_to='uploads/project/%Y/%m/%d')),
                ('project_description', models.TextField(max_length=10000)),
                ('facebook_url', models.CharField(max_length=125)),
                ('twitter_url', models.CharField(max_length=125)),
                ('youtube_url', models.CharField(max_length=125)),
                ('site_url', models.CharField(max_length=125)),
                ('is_active', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Categories')),
            ],
        ),
    ]
